#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           2
bspc config top_padding 2

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme tiling

# autostart
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
polybar &
dunst &
nitrogen --restore &
xss-lock -- slock &
